config/routes.rb
Rails.application.routes.draw do
  get "boba_shop/index"
  get "boba_shop/menu"
  get "boba_shop/order"
  get "boba_shop/confirmation"

  root "boba_shop#index"
  get "/menu" => "boba_shop#menu"
  get "/order" => "boba_shop#order"
  post "/boba_order" => "boba_shop#orderBoba"
  get "/confirmation" => "boba_shop#confirmation"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/boba_order.rb
class BobaOrder < ApplicationRecord
  # attr_accessor :flavor, :toppings, :size, :sugar, :ice

  # def initialize(params = {})
  #     @flavor = params[:flavor]
  #     @toppings = params[:toppings]
  #     @size = params[:size]
  #     @sugar = params[:sugar]
  #     @ice = params[:ice]
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/boba_shop_controller.rb
class BobaShopController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    puts "----------------- In Index -----------------"
    @allOrders = BobaOrder.all
    @slideshowImages = Dir.glob("app/assets/images/slideshow/*.png").map { |path| File.basename(path) } # Returns all image names in slideshow
    puts "# of orders = #{@allOrders.size}"
  end

  def menu
  end

  def order
  end

  def orderBoba
    puts "----------------- In Order Boba -----------------"

    flavor = params[:flavorInput]
    toppings = params[:toppingsInput] || []
    toppings_string = toppings.join(", ")
    size = params[:sizeInput]
    sugar = params[:sugarInput]
    ice = params[:iceInput]

    map = {
      "flavor" => flavor,
      "size" => size,
      "sugar" => sugar,
      "ice" => ice,
      "toppings" => toppings_string
    }

    newRow = BobaOrder.new(map)

    respond_to do |format|
      if newRow.save
        puts "Success!"
        format.html { redirect_to confirmation_path }
      else
        format.html { redirect_to "/" }
      end
    end
  end

  def confirmation
    @order = BobaOrder.order(created_at: :desc).first
    puts @order.inspect
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boba_shop_helper.rb
module BobaShopHelper
end

app/views/boba_shop/confirmation.html.erb
<nav style="background-color: #fecd1a; padding: 10px;">
    <ul style="list-style-type: none; margin: 0; padding: 0; overflow: hidden;">
        <li style="float: left; margin-right: 20px;">
            <%= link_to "Home", root_path, style: "text-decoration: none; color: black;" %>
        </li>
        <li style="float: left; margin-right: 20px;">
            <%= link_to "Menu", menu_path, style: "text-decoration: none; color: black;" %>
        </li>
        <li style="float: left; margin-right: 20px;">
            <%= link_to "Order", order_path, style: "text-decoration: none; color: black;" %>
        </li>
        <li style="float: left;">
            <%= link_to "Confirmation", confirmation_path, style: "text-decoration: none; color: black;" %>
        </li>
    </ul>
</nav>

<h1>Order Confirmation</h1>

<% if @order %>
    <table style="margin: 0 auto; text-align: center;" border="1">
        <tr>
            <th>Flavor</th>
            <th>Toppings</th>
            <th>Size</th>
            <th>Sugar Level </th>
            <th>Ice Amount </th>
        </tr>
        <tr>
            <td> <%= @order.flavor %></td>
            <td> <%= @order.toppings%></td>
            <td> <%= @order.size%></td>
            <td> <%= @order.sugar %></td>
            <td> <%= @order.ice %></td>
        </tr>
    </table>
<% else %>
    <p> No order found. </p>
<% end %> 

app/views/boba_shop/index.html.erb
<nav style="background-color: #fecd1a; padding: 10px;">
    <ul style="list-style-type: none; margin: 0; padding: 0; overflow: hidden;">
        <li style="float: left; margin-right: 20px;">
            <%= link_to "Home", root_path, style: "text-decoration: none; color: black;" %>
        </li>
        <li style="float: left; margin-right: 20px;">
            <%= link_to "Menu", menu_path, style: "text-decoration: none; color: black;" %>
        </li>
        <li style="float: left; margin-right: 20px;">
            <%= link_to "Order", order_path, style: "text-decoration: none; color: black;" %>
        </li>
        <li style="float: left;">
        <%= link_to "Confirmation", confirmation_path, style: "text-decoration: none; color: black;" %>
        </li>
    </ul>
</nav>

<h1>Welcome To The Boba Shop</h1>

<div id="slideshow-container" style="position: relative; max-width: 200; height: auto;">
    <% @slideshowImages.each_with_index do |image, i| %>
    <% if i==0 %>
        <div class="slide" style="display: block;">
    <% else %>
        <div class="slide" style="display: none;">
    <% end %>
        <p><%= image_tag "slideshow/#{image}", width: "100%" %></p>
    </div>
    <% end %>
</div>

<script>
    document.addEventListener("DOMContentLoaded", () => {
        let slides = document.querySelectorAll("#slideshow-container .slide");
        let index = 0;

        setInterval( () => {
            slides[index].style.display = "none";
            index = (index + 1) % slides.length;
            slides[index].style.display = "block";
        }, 3000);
    });
</script>

app/views/boba_shop/menu.html.erb
<nav style="background-color: #fecd1a; padding: 10px;">
    <ul style="list-style-type: none; margin: 0; padding: 0; overflow: hidden;">
        <li style="float: left; margin-right: 20px;">
            <%= link_to "Home", root_path, style: "text-decoration: none; color: black;" %>
        </li>
        <li style="float: left; margin-right: 20px;">
            <%= link_to "Menu", menu_path, style: "text-decoration: none; color: black;" %>
        </li>
        <li style="float: left; margin-right: 20px;">
            <%= link_to "Order", order_path, style: "text-decoration: none; color: black;" %>
        </li>
        <li style="float: left;">
            <%= link_to "Confirmation", confirmation_path, style: "text-decoration: none; color: black;" %>
        </li>
    </ul>
</nav>

<h1>Our Menu</h1>

<table style="width: 100%; border-spacing: 5px; margin: 0;">
    <tr>
        <td style="text-align: center;">
            <%= image_tag "classic_black_milk_tea.png", style: "max-height: 300px;"%><br>
            <strong>Classic Black Milk Tea</strong>
        </td>
        <td style="text-align: center;">
            <%= image_tag "jasmine_green_milk_tea.png", style: "max-height: 300px;"%><br>
            <strong>Jasmine Green Milk Tea</strong>
        </td>
        <td style="text-align: center;">
            <%= image_tag "oolong_milk_tea.png", style: "max-height: 300px;"%><br>
            <strong>Oolong Milk Tea</strong>
        </td>
    </tr>
    <tr>
        <td style="text-align: center;">
            <%= image_tag "thai_milk_tea.jpg", style: "max-height: 300px;"%><br>
            <strong>Thai Milk Tea</strong>
        </td>
        <td style="text-align: center;">
            <%= image_tag "taro_milk_tea.jpg", style: "max-height: 300px;"%><br>
            <strong>Taro Milk Tea</strong>
        </td>
        <td style="text-align: center;">
            <%= image_tag "matcha_milk_tea.png", style: "max-height: 300px;"%><br>
            <strong>Matcha Milk Tea</strong>
        </td>
    </tr>
    <tr>
        <td style="text-align: center;">
            <%= image_tag "honeydew_milk_tea.jpg", style: "max-height: 300px;"%><br>
            <strong>Honeydew Milk Tea</strong>
        </td>
        <td style="text-align: center;">
            <%= image_tag "wintermelon_milk_tea.jpeg", style: "max-height: 300px;"%><br>
            <strong>Wintermelon Milk Tea</strong>
        </td>
        <td style="text-align: center;">
            <%= image_tag "hokkaido_milk_tea.png", style: "max-height: 300px;"%><br>
            <strong>Hokkaido Milk Tea</strong>
        </td>
    </tr>
    <tr>
        <td style="text-align: center;">
            <%= image_tag "okinawa_milk_tea.jpg", style: "max-height: 300px;"%><br>
            <strong>Okinawa Milk Tea</strong>
        </td>
        <td style="text-align: center;">
            <%= image_tag "almond_milk_tea.jpeg", style: "max-height: 300px;"%><br>
            <strong>Almond Milk Tea</strong>
        </td>
        <td style="text-align: center;">
            <%= image_tag "coconut_milk_tea.jpeg", style: "max-height: 300px;"%><br>
            <strong>Coconut Milk Tea</strong>
        </td>
    </tr>
    <tr>
        <td style="text-align: center;">
            <%= image_tag "coffee_milk_tea.jpeg", style: "max-height: 300px;"%><br>
            <strong>Coffee Milk Tea</strong>
        </td>
        <td style="text-align: center;">
            <%= image_tag "rose_milk_tea.jpeg", style: "max-height: 300px;"%><br>
            <strong>Rose Milk Tea</strong>
        </td>
        <td style="text-align: center;">
            <%= image_tag "brown_sugar_milk_tea.jpg", style: "max-height: 300px;"%><br>
            <strong>Brown Sugar Milk Tea</strong>
        </td>
    </tr>
</table>

app/views/boba_shop/order.html.erb
<nav style="background-color: #fecd1a; padding: 10px;">
    <ul style="list-style-type: none; margin: 0; padding: 0; overflow: hidden;">
        <li style="float: left; margin-right: 20px;">
            <%= link_to "Home", root_path, style: "text-decoration: none; color: black;" %>
        </li>
        <li style="float: left; margin-right: 20px;">
            <%= link_to "Menu", menu_path, style: "text-decoration: none; color: black;" %>
        </li>
        <li style="float: left; margin-right: 20px;">
        <%= link_to "Order", order_path, style: "text-decoration: none; color: black;" %>
        </li>
        <li style="float: left;">
        <%= link_to "Confirmation", confirmation_path, style: "text-decoration: none; color: black;" %>
        </li>
    </ul>
</nav>

<h1>Order Form</h1>


<form name="BobaOrder" action="/boba_order" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <div>
        <p>Flavor:</p>
        <p>
            <input type="radio" name="flavorInput" value="Classic Black"> Classic Black<br>
            <input type="radio" name="flavorInput" value="Jasmine"> Jasmine <br>
            <input type="radio" name="flavorInput" value="Oolong"> Oolong<br>
            <input type="radio" name="flavorInput" value="Thai"> Thai<br>
            <input type="radio" name="flavorInput" value="Taro"> Taro<br>
            <input type="radio" name="flavorInput" value="Matcha"> Matcha<br>
            <input type="radio" name="flavorInput" value="Honeydew"> Honeydew<br>
            <input type="radio" name="flavorInput" value="Wintermelon"> Wintermelon<br>
            <input type="radio" name="flavorInput" value="Hokkaido"> Hokkaido<br>
            <input type="radio" name="flavorInput" value="Okinawa"> Okinawa<br>
            <input type="radio" name="flavorInput" value="Almond"> Almond<br>
            <input type="radio" name="flavorInput" value="Coconut"> Coconut<br>
            <input type="radio" name="flavorInput" value="Coffee"> Coffee<br>
            <input type="radio" name="flavorInput" value="Rose"> Rose<br>
            <input type="radio" name="flavorInput" value="Brown Sugar"> Brown Sugar<br>
            
        </p>
    </div>
    <div>
        <p>Toppings:</p>
        <p>
            <input type="checkbox" name="toppingsInput[]" value="Tapioca"> Tapioca<br>
            <input type="checkbox" name="toppingsInput[]" value="Lychee Jelly"> Lychee Jelly<br>
            <input type="checkbox" name="toppingsInput[]" value="Grass Jelly"> Grass Jelly<br>
            <input type="checkbox" name="toppingsInput[]" value="Popping Boba"> Popping Boba<br>
            <input type="checkbox" name="toppingsInput[]" value="Popping Boba"> Aloe Vera<br>
            <input type="checkbox" name="toppingsInput[]" value="Popping Boba"> Lychee Jelly<br>
            <input type="checkbox" name="toppingsInput[]" value="Popping Boba"> Rainbow Jelly<br>
            <input type="checkbox" name="toppingsInput[]" value="Popping Boba"> Coffee Jelly<br>
            <input type="checkbox" name="toppingsInput[]" value="Popping Boba"> Grass Jelly<br>
            <input type="checkbox" name="toppingsInput[]" value="Popping Boba"> Coconut Jelly<br>
        </p>
    </div>

    <div>
        <p>Size:</p>
        <p>
            <input type="radio" name="sizeInput" value="Small"> Small<br>
            <input type="radio" name="sizeInput" value="Medium"> Medium<br>
            <input type="radio" name="sizeInput" value="Large"> Large<br>
        </p>
    <div>
        <p>Sugar:</p>
        <p>
            <input type="radio" name="sugarInput" value="0%"> 0%<br>
            <input type="radio" name="sugarInput" value="25%"> 25%<br>
            <input type="radio" name="sugarInput" value="50%"> 50%<br>
            <input type="radio" name="sugarInput" value="75%"> 75%<br>
            <input type="radio" name="sugarInput" value="100%"> 100%<br>
        </p>
    </div>
    <div>
        <p>Ice:</p>
        <p>
            <input type="radio" name="iceInput" value="No Ice"> No Ice<br>
            <input type="radio" name="iceInput" value="Less"> Less Ice<br>
            <input type="radio" name="iceInput" value="Regular Ice"> Regular Ice<br>
            <input type="radio" name="iceInput" value="Extra Ice"> Extra Ice<br>
            
        </p>
    </div>

        <div>
            <p><input type="submit" value="Place Order"></p>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Boba Shop" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>